// @ts-check
/**
 * @namespace TeqFw_Cfg_Enum_Error
 * @description Immutable configuration error-code enumeration.
 */

export default Object.freeze({
  INVALID_SOURCE: "CFG_INVALID_SOURCE",
  INVALID_ENTRY: "CFG_INVALID_ENTRY",
  INVALID_SOURCE_ID: "CFG_INVALID_SOURCE_ID",
  INVALID_KEY: "CFG_INVALID_KEY",
  INVALID_RAW_VALUE: "CFG_INVALID_RAW_VALUE",
  SOURCE_FAILED: "CFG_SOURCE_FAILED",
  STORE_EMPTY: "CFG_STORE_EMPTY",
  STORE_LOADING: "CFG_STORE_LOADING",
  INVALID_NAMESPACE: "CFG_INVALID_NAMESPACE",
  LOAD_ALREADY_READY: "CFG_LOAD_ALREADY_READY",
  ILLEGAL_STATE: "CFG_ILLEGAL_STATE",
});
