// @ts-nocheck
import {test,describe} from 'node:test';import {mkdtemp,rm,writeFile as put} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {services,source,assert,deferred} from './helpers.mjs';

describe('Source lifecycle',()=>{test('Object and ProcessEnv getters run only in load',async()=>{let objectReads=0,envReads=0;const object={};Object.defineProperty(object,'TEQFW_WEB__A',{enumerable:true,get(){objectReads++;return 'a';}});const env={};Object.defineProperty(env,'TEQFW_WEB__B',{enumerable:true,get(){envReads++;return 'b';}});const s=services();const os=s.object.create(object);const ps=s.processEnv.create(env);assert.equal(objectReads,0);assert.equal(envReads,0);await os.load();await ps.load();assert.equal(objectReads,1);assert.equal(envReads,1);});test('throwing getter becomes source failure',async()=>{const object={};Object.defineProperty(object,'TEQFW_WEB__A',{enumerable:true,get(){throw new Error('secret');}});const s=services();const source=s.object.create(object);await assert.rejects(s.loader.load([source]),e=>e.code==='CFG_SOURCE_FAILED'&&!e.message.includes('secret'));});});

describe('dotenv parser',()=>{test('supports documented syntax and last duplicate',()=>{const {parser}=services();assert.deepEqual(parser.parse(`\ufeff# c\r\n export TEQFW_WEB__A = one # c\r\nTEQFW_WEB__B="x\\n y # z"\nTEQFW_WEB__C=\'literal #\'\nTEQFW_WEB__A=last`),{TEQFW_WEB__A:'last',TEQFW_WEB__B:'x\n y # z',TEQFW_WEB__C:'literal #'});});test('rejects malformed, unsupported escape and unclosed quote',()=>{const {parser}=services();for(const text of ['not assignment','A="x\\q"','A="x'])assert.throws(()=>parser.parse(text));});test('does not expand or mutate process.env',()=>{const {parser}=services();const before=process.env.TEQFW_WEB__X;assert.equal(parser.parse('TEQFW_WEB__X=$OTHER\nTEQFW_WEB__Y=$(echo no)').TEQFW_WEB__X,'$OTHER');assert.equal(process.env.TEQFW_WEB__X,before);});});

describe('RawValue',()=>{for(const value of [undefined,()=>{},Symbol('x'),1n,NaN,Infinity,new Date(),new Map(),new Set(),[,'x']])test('rejects unsupported raw value '+String(value),()=>{const {raw}=services();assert.throws(()=>raw.copy(value),e=>e.code==='CFG_INVALID_RAW_VALUE');});test('rejects non-enumerable nested property before publication',async()=>{const value={ok:true};Object.defineProperty(value,'hidden',{value:'secret',enumerable:false});const s=services();await assert.rejects(s.loader.load([source('x',[{key:'TEQFW_WEB__A',value}])]),e=>e.code==='CFG_INVALID_RAW_VALUE');assert.equal(s.store.state,'failed');assert.throws(()=>s.reader.get('TEQFW_WEB'),e=>e.code==='CFG_SOURCE_FAILED'||e.code==='CFG_INVALID_RAW_VALUE');});test('preserves accepted properties and detaches',()=>{const {raw}=services();const value={a:{b:1},list:[true,null]};const copy=raw.copy(value);assert.deepEqual(copy,value);assert.notStrictEqual(copy.a,value.a);assert.equal(Object.isFrozen(copy),false);});});

describe('Loader Store Reader',()=>{test('sequential merge and immediate detach',async()=>{const s=services();const nested={x:1};const first=source('one',[{key:'TEQFW_WEB__NESTED',value:nested}]);const second={id:'two',load:async()=>{nested.x=9;return [{key:'TEQFW_WEB__V',value:2}]}};const promise=s.loader.load([first,second]);await promise;const a=s.reader.get('TEQFW_WEB');assert.equal(a.NESTED.x,1);assert.equal(Object.isFrozen(s.store.getSnapshot()),true);});test('Reader returns fresh detached non-frozen fragments',async()=>{const s=services();await s.loader.load([source('x',[{key:'TEQFW_WEB__NESTED',value:{x:1}}])]);const first=s.reader.get('TEQFW_WEB'),second=s.reader.get('TEQFW_WEB');assert.notStrictEqual(first,second);assert.notStrictEqual(first.NESTED,s.store.getSnapshot().TEQFW_WEB__NESTED);first.NESTED.x=2;assert.equal(second.NESTED.x,1);assert.equal(Object.isFrozen(first),false);});test('invalid namespace retains context',async()=>{const s=services();await s.loader.load([]);assert.throws(()=>s.reader.get('bad'),e=>e.code==='CFG_INVALID_NAMESPACE'&&e.context.namespace==='bad');});test('operational failure retains exact canonical error',async()=>{const s=services();const failing={id:'bad',load:async()=>{throw new Error('secret')}};let failure;await assert.rejects(s.loader.load([failing]),e=>{failure=e;return e.code==='CFG_SOURCE_FAILED'&&e.context.sourceId==='bad'});assert.throws(()=>s.reader.get('TEQFW_WEB'),e=>e===failure);});test('invalid returned key stays invalid key',async()=>{const s=services();await assert.rejects(s.loader.load([source('x',[{key:'bad',value:'secret'}])]),e=>e.code==='CFG_INVALID_KEY'&&e.context.sourceId==='x');});test('concurrent loads share promise',async()=>{const s=services(),gate=deferred();const p=s.loader.load([{id:'x',load:async()=>{await gate.promise;return[];}}]);assert.equal(p,s.loader.load([]));gate.resolve();await p;});});

describe('DotenvFileSource',()=>{test('validates path through cfg error and filters keys',async()=>{const s=services();for(const options of [{},{path:''},{path:3}])assert.throws(()=>s.dotenv.create(options),e=>e.code==='CFG_INVALID_SOURCE'&&e.context.field==='path');const dir=await mkdtemp(join(tmpdir(),'cfg-'));const path=join(dir,'.env');await put(path,'TEQFW_WEB__A=value\nUNRELATED=x');const result=await s.dotenv.create({path}).load();assert.deepEqual(result,[{key:'TEQFW_WEB__A',value:'value'}]);await rm(dir,{recursive:true,force:true});});});
